language: python

dist: xenial

python:
 - "3.8"

services:
 - redis-server
 - postgresql

addons:
  postgresql: "10"

install:
 - pip install -r requirements.txt -r requirements-test.txt
 - pip install coveralls

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - psql -c 'create database mygpo_test;' -U postgres

script:
  - make check-code-format
  - pytest --cov=mygpo/ --cov-branch

after_script:
  - coveralls

env:
 - DATABASE_URL="postgres://travis:travis@localhost/mygpo_test"

notifications:
  slack:
    secure: Fsaaj7TtFhd+/HghDCZ7vDxQKCSWoY4h6IC1jLKomOQNpfgaTtwfLJQ6VeR0kkXafR2nCIC6OC30sJ7w2yAoa6qCkRJuLxWLz0Vu8L7Y1YAAHn+AIit17kym3L1QMj+rZUUtCvcfudAmP/uakZlz3NfnwrKZhmfe/NowUalNl0k=
